"""Initial schema

Revision ID: a539d128fb0b
Revises: 
Create Date: 2026-08-21 23:34:50.238486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a539d128fb0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('loc', sa.String(), nullable=True),
    sa.Column('due', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('critical', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('villageName', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('water_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('householdsUsing', sa.Integer(), nullable=True),
    sa.Column('lastTestResult', sa.String(), nullable=True),
    sa.Column('groundwaterTrend', sa.String(), nullable=True),
    sa.Column('healthCasesCount', sa.Integer(), nullable=True),
    sa.Column('riskExplanation', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('recommendedAlternativeId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recommendedAlternativeId'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_sources_id'), 'water_sources', ['id'], unique=False)
    op.create_index(op.f('ix_water_sources_name'), 'water_sources', ['name'], unique=False)
    op.create_table('health_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('householdId', sa.String(), nullable=True),
    sa.Column('patientName', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('symptoms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('sourceId', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sourceId'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_cases_householdId'), 'health_cases', ['householdId'], unique=False)
    op.create_index(op.f('ix_health_cases_id'), 'health_cases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_cases_id'), table_name='health_cases')
    op.drop_index(op.f('ix_health_cases_householdId'), table_name='health_cases')
    op.drop_table('health_cases')
    op.drop_index(op.f('ix_water_sources_name'), table_name='water_sources')
    op.drop_index(op.f('ix_water_sources_id'), table_name='water_sources')
    op.drop_table('water_sources')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
